### ISSUE TITLE
Moving LISC

### ISSUE THREAD

**Issue by TomDonoghue** [neurohackweek/DataDrivenCognitiveOntology#2]
The 'lisc' folder, in this repo, is a general utility tool for using the Pubmed E-Utils API to scrape academic papers. I'm going to move further development of this utility over to here: https://github.com/TomDonoghue/lisc

Note to Neurohackweek collaborators:
Hey all, just a quick note: although I haven't continued anything on this application in particular, in the lab we've continued to poke around at some web scraping and scientific paper analysis. To continue with some of this stuff, I'm going to copy the 'lisc' code that I had converted from my old 'ERP_SCANR' code during Neurohackweek, over to a repo on my account, so I can update that code a bit, independent of the CognitiveOntology stuff, and use it as a general paper-scraping utility. The only stuff I'm going to copy over is the 'lisc' folder, and it'll be over here - https://github.com/TomDonoghue/lisc - if anyone wants to keep track of it, etc.

**Comment by vassiki** [comment]
Thanks for the update, looking forward to see where you go with this!
